FROM mysql:latest

# Set the environment variables
ENV MYSQL_ROOT_PASSWORD=1234
ENV MYSQL_DATABASE=api_tasks

# Copy the database file into the container at /docker-entrypoint-initdb.d/
COPY ./db.sql /docker-entrypoint-initdb.d/

# Expose the MySQL port
EXPOSE 3307