version: "3.9"

services:
  database:
    build:
      context: ./
      dockerfile: Dockerfile_db
    image: database_image
    container_name: database
    env_file: ./.env
    ports:
      - 3306:3306
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 3

  api:
    depends_on:
      database:
        condition: service_healthy
    build:
      context: ./
      dockerfile: Dockerfile_api
    image: api_image
    working_dir: /usr/src/TasksAPI
    container_name: api
    restart: unless-stopped
    env_file: ./.env
    ports:
      - 8080:8080
