version: "3.9"

services:
  app:
    #   extends:
    #      file: ..\mod2\docker-compose.yml
    #      service: api
    build:
      context: ./
      dockerfile: Dockerfile
    image: app_image
    working_dir: /home/node/app
    container_name: app
    restart: unless-stopped
    depends_on:
      - api
      - database
    env_file: ./.env
    ports:
      - 3000:3000
    networks:
      - shared_network
networks:
  shared_network:
    external: true
